language: java
jdk:
  - oraclejdk8
before_install:
  - echo "<settings><servers><server><id>mvn-repo</id><configuration><httpHeaders><property><name>x-oauth-basic</name><value>\${env.TOKEN}</value></property></httpHeaders></configuration></server></servers></settings>" > ~/settings.xml
install: mvn deploy --settings ~/settings.xml
