language: java
jdk: 
  - oraclejdk8
before_install:
  - echo $env.PUBLIC_KEY > ~/.ssh/travis_rsa_64.pub
  - base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64.pub > ~/.ssh/id_rsa.pub
  - echo $env.PRIVATE_KEY > ~/.ssh/travis_rsa_64
  - base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
install: mvn deploy
